# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x15\n\x13\x41llTemplatesRequest\"\"\n\x11\x41llTemplatesReply\x12\r\n\x05names\x18\x01 \x03(\t21\n\x07Greeter\x12&\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply2R\n\x13\x41llTemplatesService\x12;\n\x0fGetAllTemplates\x12\x14.AllTemplatesRequest\x1a\x12.AllTemplatesReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=18
  _globals['_HELLOREQUEST']._serialized_end=46
  _globals['_HELLOREPLY']._serialized_start=48
  _globals['_HELLOREPLY']._serialized_end=77
  _globals['_ALLTEMPLATESREQUEST']._serialized_start=79
  _globals['_ALLTEMPLATESREQUEST']._serialized_end=100
  _globals['_ALLTEMPLATESREPLY']._serialized_start=102
  _globals['_ALLTEMPLATESREPLY']._serialized_end=136
  _globals['_GREETER']._serialized_start=138
  _globals['_GREETER']._serialized_end=187
  _globals['_ALLTEMPLATESSERVICE']._serialized_start=189
  _globals['_ALLTEMPLATESSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
